#!/bin/sh

echo ""
echo "============================================="
echo "============ Welcome to ====================="
echo "============================================="
echo "  _____         _          ___  ____         "
echo " |__  /___  ___| |_ _   _ / _ \/ ___|        "
echo "   / // _ \/ __| __| | | | | | \___ \        "
echo "  / /|  __/\__ \ |_| |_| | |_| |___) |       "
echo " /____\___||___/\__|\__, |\___/|____/        "
echo "                    |___/                    "
echo "============================================="
echo " a.k.a RustyAlpine | github.com/zestynotions "
echo "============================================="
echo ""
echo ""
echo "============================================="
echo "===== Install Windows manager and tools ====="
echo "============================================="
doas apk update
doas apk add mesa-dri-gallium sway
doas apk add autotiling zoxide fd skim starship swayr ripgrep zellij gitui procs bottom macchina tealdeer alacritty xwayland wofi swaybg wl-clipboard font-jetbrain-mono font-jetbrain-nerd font-fira-mono-nerd font-fira-code-nerd
doas apk add build-base
# gcc rustup
# rustup-init -y
sh <(wget -qO- https://raw.githubusercontent.com/zestynotions/dotfiles/master/.config/rc)
echo "All done! rebooting in "
sleep 1
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1
doas reboot
