#!/bin/sh

echo ""
echo "============================================="
echo "============ Welcome to ====================="
echo "  _____         _          ___  ____         "
echo " |__  /___  ___| |_ _   _ / _ \/ ___|        "
echo "   / // _ \/ __| __| | | | | | \___ \        "
echo "  / /|  __/\__ \ |_| |_| | |_| |___) |       "
echo " /____\___||___/\__|\__, |\___/|____/        "
echo "                    |___/                    "
echo " ~ a.k.a RustyAlpine github.com/zestynotions "
echo "============================================="

## username to be created
echo ""
echo "========================================================================"
echo "Enter name for your new normal user that will get sudo/doas priveledges:"
echo "========================================================================"
echo ""
read newuser

## activate community repo
echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >/etc/apk/repositories
echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >>/etc/apk/repositories
echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >>/etc/apk/repositories

## Enabling startup of servicves to happen in parralel
echo 'rc_parallel="YES"' >>/etc/rc.conf

## set motd
echo "Welcome to $(hostname)!" >/etc/motd

apk -U upgrade &&
	apk add libuser doas git curl zsh bat exa htop neovim seatd eudev

touch /etc/login.defs
mkdir /etc/default
touch /etc/default/useradd
echo "permit persist :wheel" >>/etc/doas.d/doas.conf

## add user
echo "=========================================="
echo "===== Create user and make home dirs ====="
echo "=========================================="
adduser -s /bin/zsh $newuser
adduser $newuser wheel
mkdir -p /home/$newuser
mkdir -p /home/$newuser/.run

setup-udev
rc-update add seatd
rc-service seatd start
adduser $newuser seat

touch /home/$newuser/.zshrc
chmod 777 /home/$newuser/.zshrc
echo "sh <(wget -qO- https://raw.githubusercontent.com/zestynotions/ZestyOS/main/alpine/zestyos_finish)" >/home/$newuser/.zshrc

echo "================================================================="
echo "========= Log in with your new User account after reboot ========"
echo "================================================================="
echo ""
echo ""
echo ""
echo "Rebooting in"
sleep 1
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1
reboot
